urls.py
from django.conf.urls import patterns, url

from EXT_GEN import views

urlpatterns = patterns('',
                       url(r'^$', views.index, name='index'),
)

models.py
from django.core.files import File
from django.core.files.temp import NamedTemporaryFile
from django import forms

from datetime import datetime, timedelta
from extGenOptimizer import extGenOptimizer

import csv
import json
import re

# Create your models here.
class UploadFileForm(forms.Form):
    studentRecordFile = forms.FileField()
    timeSlotFile = forms.FileField()

# This model parses the CSV input file into the format 
# and passes to the optimizer
class extGenOptimizer1():
    def __init__(self):
        self.examEvents = []
        self.dateFormat = "%Y-%m-%d"
        self.timeFormat = "%Y-%m-%dT%H:%M:%S"
        self.inputDateTimeFormat = "%Y-%m-%d, %H:%M"
        
    def run(self, uploadFiles):
        self.addStudentRecords(uploadFiles['studentRecordFile'])
        self.addTimeSlots(uploadFiles['timeSlotFile'])
        self.runOptimizer()
        return self.getJSONdump()

    def convertScheduleToExamEvents(self):
        self.examEvents = []
        for item in self.schedule:
            self.addExamEvent(item[0], item[1], item[2])
        for item in self.timeSlots:
            self.addBackgroundTimeSlots(item[0], item[1])

    def addExamEvent(self, title, start, end):
        examEvent = {}
        examEvent['title'] = title
        examEvent['start'] = start
        examEvent['end'] = end
        examEvent['description'] = ''
        self.examEvents.append(examEvent)

    def addBackgroundTimeSlots(self, start, end):
        backgroundTimeSlot = {}
        backgroundTimeSlot['id'] = 'timeSlots'
        backgroundTimeSlot['start'] = start
        backgroundTimeSlot['end'] = end
        backgroundTimeSlot['rendering'] = 'background'
        backgroundTimeSlot['description'] = ''
        self.examEvents.append(backgroundTimeSlot)

    def addStudentRecords(self, studentRecordFile):
        tmpFile = NamedTemporaryFile()
        for chunk in studentRecordFile.chunks():
            tmpFile.write(chunk)
        tmpFile.seek(0)
        self.studentRecords = [row for row in csv.reader(tmpFile)]
        tmpFile.close()
        # Remov header
        self.studentRecords = self.studentRecords[1:]
        return True

    def addTimeSlots(self, timeSlotFile):
        tmpFile = NamedTemporaryFile()
        for chunk in timeSlotFile.chunks():
            tmpFile.write(chunk)
        tmpFile.seek(0)
        tmpTimeSlot = [row for row in csv.reader(tmpFile)]
        tmpFile.close()
        # Remov header
        tmpTimeSlot = tmpTimeSlot[1:]
        # Parse string to actual time
        self.timeSlots = []
        for t in tmpTimeSlot:
            try:
                startTime = datetime.strptime(t[0]+", "+t[1], 
                                              self.inputDateTimeFormat)
                endTime = datetime.strptime(t[0]+", "+t[2], 
                                            self.inputDateTimeFormat)
            except:
                return False
            self.timeSlots.append([startTime, endTime])
        return True

    def runOptimizer(self, verbose=False):
        myOptimizer = extGenOptimizer()
        myOptimizer.timeSlots = self.timeSlots
        myOptimizer.studentRecord = self.studentRecords
        self.schedule = myOptimizer.run(verbose=verbose)
        self.convertScheduleToExamEvents()
            
    def getJSONdump(self):
        # Sort the exam events
        self.examEvents = sorted(self.examEvents, key = lambda e: e['start'])
        # Get first exam date
        firstExamTime = datetime.strftime(self.examEvents[0]['start'], 
                                          self.dateFormat)
        defaultDateReturnString = "defaultDate: " +  \
                                  json.dumps(firstExamTime) + ","
        # Put exam events into event JSON object
        for e in self.examEvents:
            e['start'] = datetime.strftime(e['start'], self.timeFormat)
            e['end'] = datetime.strftime(e['end'], self.timeFormat)
            e['description'] = str(e['description'])
        eventReturnString = 'events:' + json.dumps(self.examEvents) + ','
        return defaultDateReturnString + eventReturnString

if __name__ == "__main__":
    t = extGenOptimizer1()

    f = File(open('static/forms/timeSlots.csv'))
    t.addTimeSlots(f)
    f.close()

    f = File(open('static/forms/studentRecords.csv'))
    t.addStudentRecords(f)
    f.close()

    t.runOptimizer(verbose=True)

    print 'JSON'
    print t.getJSONdump()

views.py
from django.shortcuts import render, HttpResponse
from django.shortcuts import HttpResponseRedirect
from django.template import Context, Template

from models import UploadFileForm
from models import extGenOptimizer1

OPTIONS = """
header: {
left:  'prev,next today',
center: 'title',
right: 'month,agendaWeek',
},
defaultView: 'agendaWeek',
editable: true,
eventLimit: true, // allow "more" link when too many events
scrollTime: '08:00:00',
"""

# Create your views here.
def index(request):
    indexContext = {}
    indexContext['fileReturnError'] = 'false'
    events = 'events:[],'
    
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES)
        if form.is_valid():
            myOptimizerParser = extGenOptimizer1()
            events = myOptimizerParser.run(request.FILES)
            # indexContext['fileReturnError'] = 'true'
    else:
        form = UploadFileForm()
    
    indexContext['form'] = form
    indexContext['calendar_config_options'] = OPTIONS
    indexContext['calendar_events'] = events
    return render(request, 'EXT_GEN/index.html', indexContext)

templates/EXT_GEN/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset='utf-8' />
    <link href='http://fonts.googleapis.com/css?family=Kranky' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}"/>
    <link rel="stylesheet" href="{% static "css/fullcalendar.min.css" %}"/>
    <link rel="stylesheet" href="{% static "css/fullcalendar.print.css" %}" media="print"/>
    <link rel="stylesheet" href="{% static "css/ext_gen.css" %}"/>
    <script type="text/javascript" src="{% static "js/moment.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/jquery.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
    <script type="text/javascript" src="{% static "js/fullcalendar.min.js" %}"></script>
    
    <script>
      $(document).ready(function() {
      $('#calendar').fullCalendar({
      {% autoescape off %}
      {{ calendar_config_options }}
      {{ calendar_events }}
      {% endautoescape %}
      });
      });
    </script>
    <script>
      if ({{fileReturnError}}==true)
      {
      alert('Error in generating time table!!!')
      }
    </script>
    <style>
      #calendar {
      max-width: 900px;
      margin: 0 auto;
      }
    </style>
    <title> Exam Timetable Generator </title>
  </head>
  <body>
    <div class="container">
      <div class="row text-center">
        <h1 class="handWritten"> Exam Timetable Generator </h1>
	<p class="handWritten handWrittenP"> Optimizing exam timetables by maximizing revision time between exams</p>
      </div>
      <br>
      <br>
      <div class="row">
        <div class="col-md-3">
	  <div class="row">
	    <hr>
	    Assumption: Each subject is assumed to last for an hour in current version.
	    <hr>
	  </div>
          <div class="row">
            <h2 class="handWritten handWrittenH2"> Step 1 </h2>
            <p class="instructions">Download the template files</p>
            <table class="table table-bordered table-condensed">
	      <tr>
		<td>
		  <a href="{% static "forms/studentRecords.csv" %}">
		    Student Record Template
		  </a>
		</td>
	      </tr>
	      <tr>
		<td>
		  <a href="{% static "forms/timeSlots.csv" %}">
                    Available time slots Template
		  </a>		  
		</td>
	      </tr>
	    </table>
	  </div>
          <div class="row">
            <form class="form-inline"  action="/" method="post" enctype="multipart/form-data">
	      {% csrf_token %}

              <h2 class="handWritten handWrittenH2"> Step 2 </h2>
              <p class="instructions">Modify the template files and upload them</p>
	      <div class="form-group">
		<label for="id_studentRecordFile">Student record file</label>
		{{ form.studentRecordFile }}
		<label for="id_timeSlotFile">Available timeslots</label>
		{{ form.timeSlotFile }}
	      </div>
          </div>

          <div class="row">
            <h2 class="handWritten handWrittenH2"> Step 3 </h2>
            <button class="btn btn-primary btn-large btn-block" type="submit" value="Submit"> 
	      <p>Generate Time Table</p>
            </button>
          </div>
          </form>
        </div>
        <div class="col-md-9">
          <div id="calendar"></div>
        </div>
      </div>
      <div class="row text-center">
	<hr>
	Designed by <a href="http://cameronlai.com"> Cameron Lai </a>
	<hr>
      </div>
  </body>
</html>